name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:

      - name: Add Environment secrets and variables
        run: |
          echo "Running basic test suite to verify environment..."
          swift test --parallel
          echo "✅ Basic tests completed successfully"
        env:
          # Environment variables for Azure OpenAI testing (if available in Copilot environment)
          AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_DEPLOYMENT: ${{ vars.AZURE_OPENAI_DEPLOYMENT }}
      
      - name: Environment setup summary
        run: |
          echo "🎉 SwiftAzureOpenAI development environment setup complete!"
          echo ""
          echo "Environment Summary:"
          echo "  • Swift Version: $(swift --version | head -n1)"
          echo "  • Package: SwiftAzureOpenAI"
          echo "  • Tools Version: 6.0"
          echo "  • Platforms: iOS 13.0+, macOS 10.15+, watchOS 6.0+, tvOS 13.0+"
          echo "  • Dependencies: None (zero external dependencies)"
          echo "  • Build Status: ✅ Ready"
          echo "  • Test Status: ✅ Ready"
          echo ""
          echo "Copilot can now:"
          echo "  • Build and compile Swift code"
          echo "  • Run comprehensive test suites"
          echo "  • Validate package structure"
          echo "  • Test Azure OpenAI integrations (if credentials available)"
          echo "  • Perform Swift package management operations"
